name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (needed for Cordova)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajusta la versión según sea necesario

      # Check the project structure
      - name: Check project structure
        run: ls -R

      # Ensure platforms directory exists
      - name: Check platforms directory
        run: |
          if [ ! -d "platforms" ]; then
            echo "Platforms directory does not exist. Please add iOS platform first."
            exit 1
          fi

      # Ensure iOS platform exists
      - name: Check iOS platform directory
        run: |
          if [ ! -d "platforms/ios" ]; then
            echo "iOS platform directory does not exist. Please add iOS platform first."
            exit 1
          fi

      # Generate Podfile if missing
      - name: Generate Podfile (if missing)
        run: |
          if [ ! -f "platforms/ios/Podfile" ]; then
            pod init --project-directory=platforms/ios
          fi

      # Install CocoaPods dependencies for iOS
      - name: Install CocoaPods
        run: pod install --project-directory=platforms/ios

      # Build the Cordova iOS app
      - name: Build iOS app
        run: |
          xcodebuild -workspace platforms/ios/HelloCordova.xcworkspace -scheme HelloCordova -configuration Release -archivePath build/HelloCordova.xcarchive archive
          xcodebuild -exportArchive -archivePath build/HelloCordova.xcarchive -exportPath build -exportOptionsPlist platforms/ios/exportOptions.plist

      # Prepare Payload directory
      - name: Prepare Payload directory
        run: mkdir Payload
        working-directory: build

      # Move the app into the Payload directory
      - name: Move app to Payload
        run: mv HelloCordova.ipa Payload/
        working-directory: build

      # Zip the output
      - name: Zip output
        run: zip -qq -r -9 CordovaIpaExport.ipa Payload
        working-directory: build

      # Upload binaries to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/CordovaIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
