name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 游꿀 iOS Build
    runs-on: macos-latest
    steps:
      # Clona el repositorio
      - uses: actions/checkout@v3

      # Instala Flutter usando el canal estable y la arquitectura x64
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Verifica si ya existe el proyecto Flutter. Si no, lo crea autom치ticamente.
      - name: Create Flutter project if not exists
        run: |
          if [ ! -f pubspec.yaml ]; then
            flutter create .
          fi

      # Asegura que el nombre del proyecto sea v치lido en el pubspec.yaml
      - name: Ensure valid Dart package name
        run: |
          sed -i '' 's/name: IPA_final/name: ipa_final/' pubspec.yaml

      # A침adir los assets al pubspec.yaml sin duplicar la clave flutter:
      - name: Ensure assets configuration in pubspec.yaml
        run: |
          if ! grep -q "assets/html/mi_carnet_vip_canjear.html" pubspec.yaml; then
            echo "A침adiendo assets al pubspec.yaml"
            if ! grep -q "^flutter:" pubspec.yaml; then
              echo "flutter:" >> pubspec.yaml
              echo "  assets:" >> pubspec.yaml
              echo "    - assets/html/mi_carnet_vip_canjear.html" >> pubspec.yaml
            else
              if ! grep -q "assets:" pubspec.yaml; then
                sed -i '' '/flutter:/a\
          assets:
                ' pubspec.yaml
              fi
              echo "    - assets/html/mi_carnet_vip_canjear.html" >> pubspec.yaml
            fi
          fi

      # Verifica si el archivo HTML est치 en el lugar correcto
      - name: Ensure HTML file exists
        run: |
          mkdir -p assets/html
          if [ ! -f assets/html/mi_carnet_vip_canjear.html ]; then
            echo "Error: El archivo assets/html/mi_carnet_vip_canjear.html no existe."
            exit 1
          fi

      # Instala las dependencias del proyecto Flutter
      - run: flutter pub get

      # Actualiza el repositorio de pods
      - run: pod repo update
        working-directory: ios

      # Compila la versi칩n release de la app iOS sin firmar
      - run: flutter build ios --release --no-codesign

      # Crea el directorio Payload
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      # Mueve la app a la carpeta Payload
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Comprime los archivos en un archivo IPA
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Sube el archivo IPA a la secci칩n de releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
