name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 游꿀 iOS Build
    runs-on: macos-latest
    steps:
      # Clona el repositorio
      - uses: actions/checkout@v3

      # Instala Flutter usando el canal estable y la arquitectura x64
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Verifica si ya existe el proyecto Flutter. Si no, lo crea autom치ticamente.
      - name: Create Flutter project if not exists
        run: |
          if [ ! -f pubspec.yaml ]; then
            flutter create .
          fi

      # Asegura que el nombre del proyecto sea v치lido en el pubspec.yaml
      - name: Ensure valid Dart package name
        run: |
          sed -i '' 's/name: ipa/name: ipa/' pubspec.yaml

      # A침adir los assets al pubspec.yaml si no est치n presentes
      - name: Ensure assets configuration in pubspec.yaml
        run: |
          if ! grep -q "assets/html/pagina.html" pubspec.yaml; then
            echo "A침adiendo configuraci칩n de assets al pubspec.yaml"
            echo "flutter:" >> pubspec.yaml
            echo "  assets:" >> pubspec.yaml
            echo "    - assets/html/pagina.html" >> pubspec.yaml
          fi

      # Verifica si el archivo HTML est치 en el lugar correcto
