name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 游꿀 iOS Build
    runs-on: macos-latest
    steps:
      # Clona el repositorio
      - uses: actions/checkout@v3

      # Instala Flutter usando el canal estable y la arquitectura x64
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Verifica si ya existe el proyecto Flutter. Si no, lo crea autom치ticamente.
      - name: Create Flutter project if not exists
        run: |
          if [ ! -f pubspec.yaml ]; then
            flutter create .
          fi

      # A침adir los assets al pubspec.yaml si no est치n presentes
      - name: Ensure assets configuration in pubspec.yaml
        run: |
          if ! grep -q "assets/html/pagina.html" pubspec.yaml; then
            echo "A침adiendo configuraci칩n de assets al pubspec.yaml"
            echo "flutter:" >> pubspec.yaml
            echo "  assets:" >> pubspec.yaml
            echo "    - assets/html/pagina.html" >> pubspec.yaml
          fi

      # Verifica si el archivo HTML est치 en el lugar correcto
      - name: Ensure HTML file exists
        run: |
          mkdir -p assets/html
          if [ ! -f assets/html/pagina.html ]; then
            echo "Error: El archivo assets/html/pagina.html no existe."
            exit 1
          fi

      # Instala las dependencias del proyecto Flutter
      - run: flutter pub get

      # Actualiza el repositorio de pods
      - run: pod repo update
        working-directory: ios

      # Compila la versi칩n release de la app iOS sin firmar
      - run: flutter build ios --release --no-codesign

      # Crea el directorio Payload
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      # Mueve la app a la carpeta Payload
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Comprime los archivos en un archivo IPA
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Sube el archivo IPA a la secci칩n de releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"

    name: 游꿀 iOS Cordova Build
    runs-on: macos-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (needed for Cordova)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajusta la versi칩n seg칰n sea necesario

      # Install Cordova globally
      - name: Install Cordova
        run: npm install -g cordova

      # Install dependencies (if you have a package.json file)
      - name: Install dependencies
        run: npm install
        working-directory: ./  # Aseg칰rate de estar en la ra칤z del proyecto

      # Remove iOS platform if it already exists (to avoid the "Platform already added" error)
      - name: Remove iOS platform (if exists)
        run: cordova platform rm ios || true
        working-directory: ./  # Aseg칰rate de estar en la ra칤z del proyecto

      # Add iOS platform
      - name: Add iOS platform
        run: cordova platform add ios
        working-directory: ./  # Aseg칰rate de estar en la ra칤z del proyecto

      # Update iOS deployment target in Cordova project files
      - name: Update iOS deployment target
        run: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' platforms/ios/HelloCordova.xcodeproj/project.pbxproj
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' platforms/ios/CordovaLib/CordovaLib.xcodeproj/project.pbxproj

      # Clear Xcode cache (optional but can help)
      - name: Clear Xcode DerivedData
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # ** Create build.json to omit code signing **
      - name: Create build.json
        run: |
          echo '{
            "ios": {
              "release": {
                "codeSignIdentity": "",
                "provisioningProfile": "",
                "developmentTeam": ""
              }
            }
          }' > build.json
        working-directory: ./  # Aseg칰rate de estar en la ra칤z del proyecto

      # ** Check if Podfile exists, and create it if it doesn't **
      - name: Force Podfile creation if missing
        run: |
          if [ ! -f platforms/ios/Podfile ]; then
            echo "No Podfile found, creating one..."
            cd platforms/ios && pod init
          else
            echo "Podfile found, continuing..."
          fi

      # Install CocoaPods dependencies for iOS
      - name: Install CocoaPods
        run: pod install
        working-directory: platforms/ios

      # Build the Cordova iOS app (using build.json)
      - name: Build iOS app (using build.json)
        run: cordova build ios --release --device --buildConfig=build.json --no-sign
        working-directory: ./  # Aseg칰rate de estar en la ra칤z del proyecto

      # Prepare Payload directory
      - name: Prepare Payload directory
        run: mkdir Payload
        working-directory: platforms/ios/build/device

      # Move the app into the Payload directory
      - name: Move app to Payload
        run: mv HelloCordova.app/ Payload  # Cambia "HelloCordova" por el nombre de tu app
        working-directory: platforms/ios/build/device

      # Zip the output
      - name: Zip output
        run: zip -qq -r -9 CordovaIpaExport.ipa Payload
        working-directory: platforms/ios/build/device

      # Upload binaries to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: platforms/ios/build/device/CordovaIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
