name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Cordova Build
    runs-on: macos-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (needed for Cordova)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajusta la versión según sea necesario

      # Install Cordova globally
      - name: Install Cordova
        run: npm install -g cordova

      # Install dependencies (if you have a package.json file)
      - name: Install dependencies
        run: npm install
        working-directory: ./  # Asegúrate de estar en la raíz del proyecto

      # Add iOS platform (if not already added)
      - name: Add iOS platform
        run: cordova platform add ios
        working-directory: ./  # Asegúrate de estar en la raíz del proyecto

      # Install CocoaPods dependencies for iOS
      - name: Install CocoaPods
        run: pod install
        working-directory: platforms/ios

      # Build the Cordova iOS app
      - name: Build iOS app
        run: cordova build ios --release --device --no-build-config
        working-directory: ./  # Asegúrate de estar en la raíz
