name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Cordova Build
    runs-on: macos-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (needed for Cordova)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Puedes ajustar la versión según sea necesario

      # Install Cordova globally
      - name: Install Cordova
        run: npm install -g cordova

      # Install dependencies (if you have a package.json file)
      - name: Install dependencies
        run: npm install
        working-directory: ./  # Asegúrate de estar en la raíz del proyecto

      # Add iOS platform (if not already added)
      - name: Add iOS platform
        run: cordova platform add ios
        working-directory: ./  # Asegúrate de estar en la raíz del proyecto

      # Check if Podfile exists and install CocoaPods dependencies
      - name: Check for Podfile and Install CocoaPods
        run: |
          if [ -f platforms/ios/Podfile ]; then
            pod install --project-directory=platforms/ios
          else
            echo "Podfile not found. Please check if the iOS platform was added successfully."
            exit 1
          fi

      # Build the Cordova iOS app
      - name: Build iOS app
        run: cordova build ios --release --device --no-build-config
        working-directory: ./  # Asegúrate de estar en la raíz del proyecto

      # Prepare Payload directory
      - name: Prepare Payload directory
        run: mkdir Payload
        working-directory: platforms/ios/build/device

      # Move the app into the Payload directory
      - name: Move app to Payload
        run: mv HelloCordova.app/ Payload  # Cambia "HelloCordova" por el nombre de tu app
        working-directory: platforms/ios/build/device

      # Zip the output
      - name: Zip output
        run: zip -qq -r -9 CordovaIpaExport.ipa Payload
        working-directory: platforms/ios/build/device

      # Upload binaries to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: platforms/ios/build/device/CordovaIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
