name: Flutter Test

on: [push, pull_request]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run load_html_test.dart
        run: flutter load_html_test.dart
