name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      # Clona el repositorio
      - uses: actions/checkout@v3

      # Instala Flutter usando el canal estable y la arquitectura x64
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Verifica si ya existe el proyecto Flutter. Si no, lo crea automáticamente.
      - name: Create Flutter project if not exists
        run: |
          if [ ! -f pubspec.yaml ]; then
            flutter create .
          fi

      # Paso de depuración: listar el contenido del directorio
      - name: List directory content
        run: |
          echo "Contenido del directorio actual:"
          ls -la

      # Verifica si el proyecto Flutter se creó correctamente
      - name: Verify Flutter project creation
        run: |
          if [ ! -d ios ]; then
            echo "Error: El directorio ios no se creó. Asegúrate de que flutter create . se ejecute correctamente."
            exit 1
          fi

      # Reemplaza el archivo main.dart generado por el archivo Dart personalizado
      - name: Replace main.dart with custom Dart file
        run: |
          echo "Reemplazando main.dart con el archivo personalizado..."
          mv leerHTML.dart lib/main.dart

      # Verifica si el archivo HTML está en el lugar correcto (en la raíz)
      - name: Ensure HTML file exists
        run: |
          if [ ! -f mi_carnet_vip_canjear.html ]; then
            echo "Error: El archivo mi_carnet_vip_canjear.html no existe en la raíz."
            exit 1
          else
            echo "El archivo mi_carnet_vip_canjear.html existe en la raíz, moviéndolo a assets/html..."
            mkdir -p assets/html
            mv mi_carnet_vip_canjear.html assets/html/
          fi

      # Asegúrate de que los assets están definidos en pubspec.yaml sin duplicar "flutter:"
      - name: Add assets to pubspec.yaml
        run: |
          if ! grep -q "assets/html/mi_carnet_vip_canjear.html" pubspec.yaml; then
            echo "Verificando si ya existe la sección de assets..."
            if grep -q "flutter:" pubspec.yaml; then
              # Si la sección flutter ya existe, agregar los assets
              echo "Agregando assets a la sección existente de flutter..."
              awk '/flutter:/{print;print "  assets:\n    - assets/html/mi_carnet_vip_canjear.html";next}1' pubspec.yaml > pubspec_temp.yaml
              mv pubspec_temp.yaml pubspec.yaml
            else
              # Si no existe la sección flutter, agregar todo
              echo "Agregando sección flutter con assets..."
              echo -e "\nflutter:\n  assets:\n    - assets/html/mi_carnet_vip_canjear.html" >> pubspec.yaml
            fi
          fi

      # Instala las dependencias del proyecto Flutter
      - run: flutter pub get

      # Actualiza el repositorio de pods
      - name: Update CocoaPods repository
        run: pod repo update
        working-directory: ios

      # Compila la versión release de la app iOS sin firmar
      - run: flutter build ios --release --no-codesign

      # Crea el directorio Payload
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      # Mueve la app a la carpeta Payload
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Comprime los archivos en un archivo IPA
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Sube el archivo IPA a la sección de releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
